apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
data:
  rabbitmq.conf: |
    vm_memory_high_watermark.relative = 0.6
    channel_max = 2048
    heartbeat = 60
    loopback_users.guest = false
